### ISSUE TITLE
Pagina Iniziale (p00Home.html) Home page

### ISSUE THREAD

**Issue by MatteoLalicata** [lestopasso/ASL4aii1718#19]
**ATTENZIONE: il file è stato rinominato p00Home.html, era p00Index.html)** 
Modificare header con immagine nuova. (Da ricevere)
Ridimensionamento immagine.
Scritta a fianco all'immagine da ridurre di dimensioni (vedere stampa).
Impostare testo "principale" su due colonne.
Aggiungere due bottoni sotto, centrati: info e indice.

**Comment by luigiferrari1001** [comment]
Finita
