### ISSUE TITLE
Introduzione contiene un colore delle font cablato

### ISSUE THREAD

**Issue by lestopasso** [lestopasso/ASL4aii1718#2]
File: p01Introduzione.html
Eliminare il colore cablato con opportuna classe per i numeri delle domande.
La classe deve essere definita nel css relativo come **NumerazioneRisposte**

**Comment by ghost** [comment]
Ho creato la classe nel CSS ma come Colore invece che NumerazioneRisposte, poichè ho notato che quel colore è sempre lo stesso per i pannelli basati sull'acqua.
