### ISSUE TITLE
Pannello 1

### ISSUE THREAD

**Issue by MatteoLalicata** [lestopasso/ASL4aii1718#20]
**DA VERIFICARE**

INTRODUZIONE:
Loghi no responsive.
Titolo più grande.
Distanziamento di poco del testo e riduzione della larghezza della griglia che lo contiene.

SOLUZIONE:
Allineare il titolo al testo.
centrare l'immagine del rubinetto con il testo.
_Se possibile_ ritagliare l'immagine

IPERTESTI:
Immagini più piccole.
Spazio ridotto tra immagine e testo.
Sistemare i loghi.

**Comment by luigiferrari1001** [comment]
Aggiungere modifiche evidenziate dalle prove del 6.12.2017 (i.e. bordi laterali uniformi, grazie del titolo...)

**Comment by luigiferrari1001** [comment]
Completo
