### ISSUE TITLE
Pagina 2 - To do list - Macciò Vitali 

### ISSUE THREAD

**Issue by MatteoLalicata** [lestopasso/ASL4aii1718#21]
INTRODUZIONE:
Immagine dei rubinetti leggermente più piccole. PER ORA NO
Rimuovere l'immagine di footer e aggiornare i loghi. FATTO LF
L'immagine del bottone è più grande di quella delle altre pagine. FATTO LF
Non va bene l'organizzazione logica del testo. Deve essere organizzato su due righe con ciascuna due colonne, la prima riga con  i testi, la seconda con  i punti. Eliminare le table ed utilizzare invece row e col.
Non ci deve essere sfasamento: vedi screenshot:
![pannello2conerrore](https://user-images.githubusercontent.com/32217112/33772361-a9dca458-dc34-11e7-9c2e-c348a93a7a83.JPG)
FATTO LF
I colori dei punti devono usare la classe Colore e non il valore cablato  nel codice. FATTO LF
Nel testo c'e' un apostrofo non coretto. FATTO LF

SOLUZIONE:
Testo su due colonne. FATTO
Immagine sotto il testo. FATTO
Immagine viene deformata a causa dell'uso errato di section. FATTO LF
Puntare alla pagina 3. FATTO
Immagine ridimensionata per far stare tutto nel formato standard. FATTO LF  (in master.css introdotta la classe ImgResize80) 

IPERTESTO:
Testo più stretto (aumentare di poco il margine) e distanziarlo un po' dall'immagine.
Mancano i loghi.

Rivedere le dimensioni in kB delle immagini ed eventualmente ridurle.

**Comment by luigiferrari1001** [comment]
Completo
