### ISSUE TITLE
Pagina 4 - Marin Bozzano

### ISSUE THREAD

**Issue by MatteoLalicata** [lestopasso/ASL4aii1718#25]
INTRODUZIONE:
Aggiungere bordo all'immagine.
Sostituire le immagini "trattini" con testo e modificarne il colore. ( _  _  _  _  _ ) FATTO 21.11.2017

SOLUZIONE:
Allineare titolo.
Riadattare testo. FATTO IN PARTE LF
Valutare ridimensionamento immagine. 

IPERTESTO:
Nell'ipertesto Fognature diminuire lo spazio tra immagine e testo
Ipertesto fognature: vedere issue #39

**Comment by luigiferrari1001** [comment]
Completo
