### ISSUE TITLE
Pagina 5 - Gattullo, Anselmo, Amenta

### ISSUE THREAD

**Issue by MatteoLalicata** [lestopasso/ASL4aii1718#26]
INTRODUZIONE:
Titolo più grosso. FATTO
Immagine più piccola.  FATTO
Adattare il testo all'immagine. FATTO
Loghi da sistemare FATTO

SOLUZIONE:
Header da modificare ( 1 -> 5). FATTO
Cambiare l'immagine. (p05bistecca). FATTO
Puntare alla pagina 6. FATTO
Allineamento margine destro della parte sotto è errato. FATTO
Non ci deve esserci spazi prima dei :  FATTO
Dopo "una bottiglia di vino" ci sono : al posto di una a. FATTO

**Comment by luigiferrari1001** [comment]
Completo.
