### ISSUE TITLE
Analisi proposta della Home page nuova (Stana, Suman, La Licata) 

### ISSUE THREAD

**Issue by luigiferrari1001** [lestopasso/ASL4aii1718#27]
Verificare se possono andare bene i colori, disegni etc.

[homepage sei ecologico.docx](https://github.com/lestopasso/ASL4aii1718/files/1501476/homepage.sei.ecologico.docx)

**Comment by lucadilisio** [comment]
I nostri pareri (Io, La Licata, Stana, Suman) sono:
-La barra arancione va bene, se si potesse fare leggermente più chiaro il colore sarebbe meglio
-Il bambino più colorato, è molto sbiadito
-I colori delle icone sono spenti
-Nei bottoni la 'i' delle Info secondo noi sarebbe da fare più snella, in modo da renderla uguale al bottone sulla sinistra

**Comment by ghost** [comment]
ATTENZIONE: il testo NON è quello del docuemnto word ma quello attualmente presente nella p00Index.html.
Vanno aggiunte le icone dei pulsanti e sostituita la barra in alto.
Immagini da utilizzare:

![banda top con gatto](https://user-images.githubusercontent.com/24865799/33367560-52e71058-d4ef-11e7-9801-1abdfc5dcead.png)
![acqua](https://user-images.githubusercontent.com/24865799/33367624-80585a24-d4ef-11e7-8604-c4e719f4ad59.png)
![ambiente](https://user-images.githubusercontent.com/24865799/33367626-8085d896-d4ef-11e7-91f4-f60e1eb12fe3.png)
![energia](https://user-images.githubusercontent.com/24865799/33367627-80ad4854-d4ef-11e7-81cd-74e96e1279e6.png)
![home](https://user-images.githubusercontent.com/24865799/33367629-80d3fd6e-d4ef-11e7-9afe-4975872a5f76.png)
![info](https://user-images.githubusercontent.com/24865799/33367630-8100f918-d4ef-11e7-9ecd-51a54a224d74.png)

**Comment by luigiferrari1001** [comment]
Fatto
