### ISSUE TITLE
Pannello 8  (Lucarelli, Stana) + Morelli per css - Introduzione

### ISSUE THREAD

**Issue by ghost** [lestopasso/ASL4aii1718#32]
introduzione: 
togliere lo spazio prima di "Prova a indovinare": ATTENZIONE forse è un problema del css dopo gli elenchi puntati FATTO
Puntini dell'elenco in verde. FATTO
Link ipertesto va in verde (dello stessa tonalità del pannello e dei puntini dell'elenco) (#23) FATTO

**Comment by luigiferrari1001** [comment]
Modifiche fatta da Stana. E' stato necessario rivedere titoli, formattazione paragrafo dopo ul.
Chiuso
