### ISSUE TITLE
Pannnello 11 - Petri, Di Lisio, Siri

### ISSUE THREAD

**Issue by ghost** [lestopasso/ASL4aii1718#33]
Introduzione 
Immagine da ridurre un po' (solo questa), aggiungendo magari un paddding a destra e sinistra) e incorniciare (è un rebus) con bordo sottile (vedi anche pannello 4).
Il vocabolo energheia va messo in alfabeto GRECO compresi gli accenti e gli spiriti.
Link va in giallo (verificare la visibilità)

Soluzione:
colore iperlink in giallo (verificare visibilità)
Testo da modificare (vedi Issue #7)

Ipetesti:
Ipertesto Cogenerazione ha testo modificatio (vedi issue #7 )

**Comment by lucadilisio** [comment]
Commit (email inviata il 20/12/17)
--CSS-- (Modificato con l'autorizzazione di Morelli)
Modifica del colore dei link nei file "pannelli_acqua.css", "pannelli_ambiente.css", "pannelli_energia.css"
I link adesso sono colorati in tutti i progetti.

--Pannello 11--
~Introduzione
Immagine ridotta (padding-left/right: 5px;)
Rebus incorniciato con un bordo giallo (Nel pannello 4 non vi è alcun bordo)
Vocabolo modificato in alfabeto Greco.
Link in giallo visibili (modificato con Morelli, 'CSS Morelli.zip')
~Soluzione
Link in giallo visibili (modificato con Morelli, 'CSS Morelli.zip')
Testo Soluzione sostituito
~Ipertesto 4
Testo Cogenerazione sostituito

**Comment by luigiferrari1001** [comment]
Apportate diverse modifiche alla consegna.
Dovrebbe essere quasi definitivo.

**Comment by luigiferrari1001** [comment]
Terminate modifiche alla soluzione per correggere allineamenti. (LF)
