### ISSUE TITLE
Pannello 12 - Sanyaolu, Insinna

### ISSUE THREAD

**Issue by ghost** [lestopasso/ASL4aii1718#34]
Soluzione:
Ancora da rivedere completamente.
I link vanno in giallo (#23)
manca collegamento a ipertesto.
Controllare operatività  dei pulsanti

Ipertesto:
Pulsante del colore giusto.

**Comment by LucaInsinna** [comment]
Mi sono fatto dire da Di Lisio come dovessi commentare, infatti in precedenza ho chiesto la proposta di modifica dei file
Commit (email inviata il 21/12/2017)
--Pannello 12--
~Soluzione
Link combustibili fossili introdotto con tanto di collegamento a ipertesto
Controllato operatività dei pulsanti
~Ipertesto
Messo il colore dell'esci giallo

**Comment by luigiferrari1001** [comment]
Finite le modifiche con spostamento dei titoli.
