### ISSUE TITLE
Pannello 14 - Sanyaolu, Insinna

### ISSUE THREAD

**Issue by ghost** [lestopasso/ASL4aii1718#35]
Sistemare le colonne , gli spazi tra le righe, le dimensioni dei titoli, etc.
#23 OK, link agli ipertesti NON CE NE SONO.
Rivedere dimensioni immagini sull'hard disk

**Comment by LucaInsinna** [comment]
Come le dovrei modificare?

**Comment by luigiferrari1001** [comment]
Secondo il documento pdf (dovrebbe essere su P o scaricabile qui:
http://progetto6ecologico.altervista.org/PannelliDocumenti/Totem_bassa-def.pdf)
e con la stessa struttura degli altri pannelli (ad esempio il pannello 1
dovrebbe essere tra quelli più aggiornati).
LF

2017-12-21 10:07 GMT+01:00 LukeWare <notifications@github.com>:

**Comment by luigiferrari1001** [comment]
Eseguite le modifiche. Non verificate le dimensioni delle immagini. (LF)
