### ISSUE TITLE
Vanno cambiati i loghi in fondo alle pagine

### ISSUE THREAD

**Issue by lestopasso** [lestopasso/ASL4aii1718#5]
Ecofan è da estrarre del file pdf (quello in seconda pagina senza circolo intorno)
[BOLLINO e LOGO ECOFAN DEF.pdf](https://github.com/lestopasso/ASL4aii1718/files/1341089/BOLLINO.e.LOGO.ECOFAN.DEF.pdf)

Ordine di presentazione: **Iren - ecofan- fondazione** ma è da verificare se non viene meglio con ecofan in mezzo.

**Comment by luigiferrari1001** [comment]
Terminato con versione del 13.11.2017
