### ISSUE TITLE
Le estensioni dei nomi delle immagini DEVONO essere tutti in minuscolo

### ISSUE THREAD

**Issue by luigiferrari1001** [lestopasso/ASL4aii1718#71]
Il problema è che per gitHub risultano uguali, quindi modificandoli in locale non vengono trasferiti in remoto.
In questo momento sul sito le immagini che avevano nome uguale sono duplicati.
Possibile workaround: cancellare da github tutti i file con estensione .PNG, commit, ricaricarceli con le estensioni .png, commit.

**Comment by luigiferrari1001** [comment]
NON VA BENE! i file delle immagini sono ora nella radice e nella cartella immagini ci sono quelli con le maiuscole!

**Comment by ghost** [comment]
Uh, appena mi rimetto davanti a un PC risolvo
