### ISSUE TITLE
Immagini in copia

### ISSUE THREAD

**Issue by luigiferrari1001** [lestopasso/ASL4aii1718#92]
p14SmartCity.png (italiano) ce ne sono due copie doi dimensione diverse. Lasciarne solo quella di dimensioni minori con nome ovviamente valido.

**Comment by Loryxz2000** [comment]
Tutto ok, abbiamo liberato fino a 77MB

Il mar 20 nov 2018, 09:53 Luigi Ferrari <notifications@github.com> ha
scritto:

**Comment by luigiferrari1001** [comment]
OK
